### ISSUE TITLE
Track download failed: 404 Client Error

### ISSUE THREAD

**Issue by Ethan930717** [uhwot/orpheusdl-kkbox#17]
HI, I encountered the following error message while downloading and would like to know how to fix it. The program was working normally yesterday. The error message is:

Warning: Track download failed: 404 Client Error: Not Found for url: https://api-kkbox-manifest.qp.kkbox.com.tw/v3/C4gHf56-******?mtime=4&ver=06120082&os=android&osver=13&dist=0021&dist2=0021&sid=V14utymhm850000001.0KF1001.lFe000000000000K335PoQDS001.eDvQ30f7&play_mode=android&src=flac_24_download_kkdrm&__gda__=1705566521_*****

**Comment by gooeygreenmuffins** [comment]
How did you fix this? I'm getting the same error.

**Comment by Gustaco112m345x** [comment]
> ¿Cómo arreglaste esto? Recibo el mismo error.


Probably their links that wish to download do not belong to the same country with which they registered their accounts

**Comment by gooeygreenmuffins** [comment]
> > ¿Cómo arreglaste esto? Recibo el mismo error.
> 
> Probably their links that wish to download do not belong to the same country with which they registered their accounts

I made sure the link was for the country I registered in and used a VPN to be in said country, so I'm not sure that's it. The band itself isn't from the country I registered in, but that's never been a problem before and I can still access the album in question just fine on the service.
