### ISSUE TITLE
Unable to login even with VPN

### ISSUE THREAD

**Issue by sooyongjie** [uhwot/orpheusdl-kkbox#19]
Country: Malaysia
VPN service: NordVPN
Issue 1: Unable to login with Taiwan/Hong Kong VPN (IP address is in unsupported region)
Issue 2: KKBOX is available in my country (no loseless). Is it not possible to download standard quality with my account?

Btw, I could not DM you via Telegram. You did not include your username in the channel.

**Comment by sooyongjie** [comment]
Oh btw, I could not DM you via Telegram. You did not include your username in the channel

**Comment by uhwot** [comment]
1: i'm not having issues with VPNs, make sure the module is updated and the secret_key in settings is correct
2: you cannot download FLACs from malaysia, while everything else should download fine

**Comment by sooyongjie** [comment]
Yeah turns out I pasted in the wrong secret key, bruh. Thanks sar for the help 💖
