### ISSUE TITLE
Playlist bug

### ISSUE THREAD

**Issue by frankwu8765** [uhwot/orpheusdl-kkbox#2]
when i'm downloading a playlist,
the tracknames of 16bit songs are fine,such as:001. SUPER JUNIOR - Mango [16bit 44.1kHz]
but the tracknames of 24bit songs are strange,such as:009. SUNMI - Heart Burn [24bit NonekHz]
by the way,it can't skip the downloaded tracks,it will download the tracks once again

**Comment by uhwot** [comment]
the sample rate isn't known on 24-bit flacs until it's actually downloaded, that's why it shows up as "None"
you should prob ask the orpheusdl devs about that

as for the tracks not skipping, idk it works fine for me. maybe you have that disabled in the settings?

**Comment by frankwu8765** [comment]
> the sample rate isn't known on 24-bit flacs until it's actually downloaded, that's why it shows up as "None" you should prob ask the orpheusdl devs about that
> 
> as for the tracks not skipping, idk it works fine for me. maybe you have that disabled in the settings?

thank you so much!i will check the settings
