### ISSUE TITLE
[Question] Looking for Metadata

### ISSUE THREAD

**Issue by Slyyxp** [uhwot/orpheusdl-kkbox#6]
Looking through `v1/album` and `album_more.php` responses and I'm looking for 2 specific pieces of information I don't see.

1. Release date (Including Day)
2. Disc Number/Disc Totals

Release date is included here https://www.kkbox.com/hk/tc/album/4qlW631FwYJTRREl0H with the day of release.
There is a release date in the `v1/album` response but the day isn't included, KKBOX clearly store this information somewhere though, just wondering if it's included with an implemented endpoint in `KkboxAPI()` to save me having to scrape this.

Also no sign of any disc information for multi-disc albums. Not sure this is stored at all though. 
Example case: https://play.kkbox.com/album/P_G_Wke-KjgS6ditQ-

**Comment by uhwot** [comment]
as far as i'm aware full release dates can only be retrieved via their public API, including ISRCs
https://docs-en.kkbox.codes/#get-/tracks/{track_id}
i kinda forgot about implementing that, though it would probably increase latency a fair bit considering how slow their servers are

i haven't seen multi-disc info in any of their APIs, so i don't think i can do much there

**Comment by Slyyxp** [comment]
> as far as i'm aware full release dates can only be retrieved via their public API, including ISRCs
[https://docs-en.kkbox.codes/#get-/tracks/{track_id}](https://docs-en.kkbox.codes/#get-/tracks/%7Btrack_id%7D)
i kinda forgot about implementing that, though it would probably increase latency a fair bit considering how slow their servers are

Thanks for the info, i'll implement this locally. The slow-down will have to be dealt with because this information is unfortuantely required for my use-case.

> i haven't seen multi-disc info in any of their APIs, so i don't think i can do much there

Shame.

Thanks for quick response.
