### ISSUE TITLE
[Question] Volume Levelling

### ISSUE THREAD

**Issue by Slyyxp** [uhwot/orpheusdl-kkbox#7]
Had an additional question.
Is every single FLAC from KKBOX dampened? Seems that way as far as I can see.

-7dB to -10.8dB, can I circumvent this?

Perhaps an issue specific to `kkdrm`? Every other KKBOX file I've seen seems to be encoded with `Lavf58.29.100` and have no volume levelling whatsoever.

**Comment by uhwot** [comment]
you probably have replay gain enabled in your audio player, try disabling it first

**Comment by Slyyxp** [comment]
Popping the replay gain tags solved this.
Was expecting `Lavf` and not `referencelibFLAC` as the encoder.
Files obtained elsewhere and through the site's own sample are encoded with `Lavf` without these tags appended.

Thanks.
