### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by sansalayne** [uhwot/orpheusdl-kkbox#8]
I get this error when I try to download, it has not happened to me until today.

**Comment by Yuq-q** [comment]
![image](https://user-images.githubusercontent.com/57177286/212469019-0bd232a2-ffbb-425f-97f5-421755e2f3e6.png)

yep

**Comment by uhwot** [comment]
works for me on a trial account at least, can't really test on a premium account since i don't have any lol

can you login on the official kkbox android/ios app or does it not work there too?

**Comment by sansalayne** [comment]
It works perfectly when using a VPN, I will close the issue.
